.PHONY : build view info history insert readme clean
# Andrew Yaros - CS265 - Assignment 4 - Bank Acounts - makefile
build :
	@# "Not much to do here.  I did this in Python"
	chmod +755 accounts.py

view :
	@\less accounts.py

info :
	./accounts.py -i

history :
	./accounts.py -h

insert :
	./accounts.py -t

readme :
	@\less README

clean :
	@\rm *.pyc
